# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch: 
  watch:
    types: [started]
  schedule: 
    - cron: 21 23,11 * * *
    - cron: 01 5,17 * * *

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go 1.x.y
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        check-latest: true
    - name: Set variables and timezone
      run: |
          sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          
    - name: Run main.go
      run: go run main.go
      
    - name: Create output.txt
      run: |
          echo "# Title: MP Master Adguard Home Rules List" > output.txt
          echo "# Verison: $(date +%Y%m%d%H%M)" >> output.txt
          echo "# Expires: around 1 day" >> output.txt
          echo "# Below are the links of the adblock rules" >> output.txt
          while IFS= read -r line; do echo "# $line" >> output.txt; done < master.txt
          cat out.txt >> output.txt
          
    - name: Create output_simple.txt
      run: |
          echo "# Title: MP Simple Adguard Home Rules List" > output_simple.txt
          echo "# Verison: $(date +%Y%m%d%H%M)" >> output_simple.txt
          echo "# Expires: around 1 day" >> output_simple.txt
          echo "# Below are the links of the adblock rules" >> output_simple.txt
          while IFS= read -r line; do echo "# $line" >> output_simple.txt; done < simple.txt
          cat out_simple.txt >> output_simple.txt
          
      
    - name: move output file
      run: |
          mkdir -p ./publish/
          cp ./output*.txt ./publish/
          

      
    - name: Release and upload assets
      uses: softprops/action-gh-release@v0.1.6
      with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./publish/*
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Git push assets to "release" branch
      run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "112455607+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

    - name: Purge jsdelivr CDN
      run: |
          cd publish || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
          done
    
    - name: Commit *.txt
      run: |
         echo `date +"%Y-%m-%d %H:%M:%S"` ZJC CKC >> output.log
         git config --global user.email ${{ secrets.EMAIL }}
         git config --global user.name ${{ secrets.NAME }}
         git add ./output*
         git commit -am "Updated"
         git push
