# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch: 
  watch:
    types: [started]
  schedule: 
    - cron: 21 23,11 * * *
    - cron: 01 5 * * *

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go 1.x.y
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        check-latest: true
    - name: Set folder condition, variables and timezone
      run: |
          sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          rm -f ./out*.txt
          
    - name: Run main.go
      run: |
          go run main.go "./setting/full_rules.txt" out_full.txt "./setting/custom.txt"
          go run main.go "./setting/medium_rules.txt" out_med.txt "./setting/custom.txt"
          go run main.go "./setting/min_rules.txt" out_min.txt "./setting/custom.txt"
      
    - name: Create output_full.txt
      run: |
          echo "# Title: MP Fully block Adguard Home Rules List" > output_full.txt
          echo "# Verison: $(date +%Y%m%d%H%M)" >> output_full.txt
          echo "# Expires: around 1 day" >> output_full.txt
          echo "# Below are the links of the adblock rules" >> output_full.txt
          while IFS= read -r line; do echo "# $line" >> output_full.txt; done < "./setting/full_rules.txt"
          echo "####################################################################################" >> output_full.txt
          cat out_full.txt >> output_full.txt
          echo "####################################################################################" >> output_full.txt
          
    - name: Create output_medium.txt
      run: |
          echo "# Title: MP Medium Adguard Home Rules List" > output_medium.txt
          echo "# Verison: $(date +%Y%m%d%H%M)" >> output_medium.txt
          echo "# Expires: around 1 day" >> output_medium.txt
          echo "# Below are the links of the adblock rules" >> output_medium.txt
          while IFS= read -r line; do echo "# $line" >> output_medium.txt; done < "./setting/medium_rules.txt"
          echo "####################################################################################" >> output_medium.txt
          cat out_med.txt >> output_medium.txt
          echo "####################################################################################" >> output_medium.txt
          
    - name: Create output_min.txt
      run: |
          echo "# Title: MP Min Adguard Home Rules List" > output_min.txt
          echo "# Verison: $(date +%Y%m%d%H%M)" >> output_min.txt
          echo "# Expires: around 1 day" >> output_min.txt
          echo "# Below are the links of the adblock rules" >> output_min.txt
          while IFS= read -r line; do echo "# $line" >> output_min.txt; done < "./setting/min_rules.txt"
          echo "####################################################################################" >> output_min.txt
          cat out_min.txt  >> output_min.txt
          echo "####################################################################################" >> output_min.txt
          
    - name: move output file
      run: |
          mkdir -p ./publish/
          cp ./output*.txt ./publish/
          cp ./output*.txt ./rules/
          cp ./output_min.txt output_simple.txt
          cp ./output_full.txt output.txt
          
    - name: Release and upload assets
      uses: softprops/action-gh-release@v0.1.6
      with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./publish/*
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Git push assets to "release" branch
      run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "112455607+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

    - name: Purge jsdelivr CDN
      run: |
          cd publish || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
          done
    
    - name: Commit *.txt
      run: |
         git config --global user.email ${{ secrets.EMAIL }}
         git config --global user.name ${{ secrets.NAME }}
         git add ./rules/output* ./output.txt ./output_simple.txt
         git diff | tee -a ./rules/commit.log
         echo `date +"%Y-%m-%d %H:%M:%S"` ZJC CKC >> ./rules/date.log
         git add ./rules/commit.log ./rules/date.log
         git commit -m "${{ env.RELEASE_NAME }}"
         git push
