on:
  workflow_dispatch:
  schedule: 
    - cron: 21 1,3,5,6,9,11,13,15,17,19,21,23 * * *
    - cron: 01 0,2,4,6,8,10,12,14,16,18,20,22 * * *

name: ⏫ Copying Setting to other page

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Copy the 'post' folder
    - name: Push posts
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'setting/' # Folder to copy
        destination_repo: '${{ secrets.PATH }}' # Target repo
        destination_folder: '/' # Folder where to copy it
        user_email: '${{ secrets.EMAIL1 }}'
        user_name: '${{ secrets.NAME1 }}'
        commit_message: "SYNC FROM SOURCE"
        git_server: 'github.com'
