# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: test

on:
  workflow_dispatch: 
  watch:
    types: [started]
  schedule: 
    - cron: 21 23,11 * * *
    - cron: 01 5 * * *

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go 1.x.y
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        check-latest: true
        
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
          node-version: '12.x'
    - run: npm install
    
    - name: Install hostlist-complier
      run: npm i -g @adguard/hostlist-compiler

